[package]
name = "snake"
version = "0.1.0"
authors = ["willgough <williamhenrygough@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.18"
piston_window = "0.74.0"